export const caseData = [
  {
    'Case ID': 'CASE-1001',
    'Requested Date/Time': '2023-05-15T09:23:45Z',
    Type: 'Technical Support',
    'Requested From': 'IT Department',
    'Assigned To': 'John Smith',
    Status: 'open',
  },
  {
    'Case ID': 'CASE-1002',
    'Requested Date/Time': '2023-05-16T14:12:30Z',
    Type: 'Billing Inquiry',
    'Requested From': 'Finance Department',
    'Assigned To': 'Emily Johnson',
    Status: 'pending',
  },
  {
    'Case ID': 'CASE-1003',
    'Requested Date/Time': '2023-05-17T11:45:22Z',
    Type: 'Access Request',
    'Requested From': 'HR Department',
    'Assigned To': 'Michael Brown',
    Status: 'completed',
  },
  {
    'Case ID': 'CASE-1004',
    'Requested Date/Time': '2023-05-18T16:30:15Z',
    Type: 'Complaint',
    'Requested From': 'Customer Service',
    'Assigned To': 'Sarah Williams',
    Status: 'escalated',
  },
  {
    'Case ID': 'CASE-1005',
    'Requested Date/Time': '2023-05-19T08:15:33Z',
    Type: 'Software Bug',
    'Requested From': 'Development Team',
    'Assigned To': 'David Miller',
    Status: 'open',
  },
  {
    'Case ID': 'CASE-1006',
    'Requested Date/Time': '2023-05-20T13:22:10Z',
    Type: 'Hardware Issue',
    'Requested From': 'Operations',
    'Assigned To': 'Jessica Davis',
    Status: 'pending',
  },
  {
    'Case ID': 'CASE-1007',
    'Requested Date/Time': '2023-05-21T10:05:47Z',
    Type: 'Security Concern',
    'Requested From': 'Security Team',
    'Assigned To': 'Robert Wilson',
    Status: 'completed',
  },
  {
    'Case ID': 'CASE-1008',
    'Requested Date/Time': '2023-05-22T15:18:29Z',
    Type: 'Data Request',
    'Requested From': 'Analytics Team',
    'Assigned To': 'Jennifer Taylor',
    Status: 'escalated',
  },
  {
    'Case ID': 'CASE-1009',
    'Requested Date/Time': '2023-05-23T09:42:51Z',
    Type: 'Training Request',
    'Requested From': 'Learning & Development',
    'Assigned To': 'William Anderson',
    Status: 'open',
  },
  {
    'Case ID': 'CASE-1010',
    'Requested Date/Time': '2023-05-24T14:37:14Z',
    Type: 'Vendor Inquiry',
    'Requested From': 'Procurement',
    'Assigned To': 'Elizabeth Martinez',
    Status: 'pending',
  },
  {
    'Case ID': 'CASE-1011',
    'Requested Date/Time': '2023-05-25T11:20:38Z',
    Type: 'Policy Question',
    'Requested From': 'Legal Department',
    'Assigned To': 'James Thomas',
    Status: 'completed',
  },
  {
    'Case ID': 'CASE-1012',
    'Requested Date/Time': '2023-05-26T16:45:02Z',
    Type: 'Facilities Issue',
    'Requested From': 'Office Management',
    'Assigned To': 'Patricia Hernandez',
    Status: 'escalated',
  },
  {
    'Case ID': 'CASE-1013',
    'Requested Date/Time': '2023-05-27T08:30:19Z',
    Type: 'Network Problem',
    'Requested From': 'IT Infrastructure',
    'Assigned To': 'Christopher Moore',
    Status: 'open',
  },
  {
    'Case ID': 'CASE-1014',
    'Requested Date/Time': '2023-05-28T13:15:42Z',
    Type: 'Account Setup',
    'Requested From': 'Onboarding Team',
    'Assigned To': 'Linda Martin',
    Status: 'pending',
  },
  {
    'Case ID': 'CASE-1015',
    'Requested Date/Time': '2023-05-29T10:08:27Z',
    Type: 'Document Review',
    'Requested From': 'Compliance',
    'Assigned To': 'Daniel Jackson',
    Status: 'completed',
  },
  {
    'Case ID': 'CASE-1016',
    'Requested Date/Time': '2023-05-30T15:33:55Z',
    Type: 'System Upgrade',
    'Requested From': 'Engineering',
    'Assigned To': 'Barbara White',
    Status: 'escalated',
  },
  {
    'Case ID': 'CASE-1017',
    'Requested Date/Time': '2023-05-31T09:17:08Z',
    Type: 'Password Reset',
    'Requested From': 'Help Desk',
    'Assigned To': 'Matthew Thompson',
    Status: 'open',
  },
  {
    'Case ID': 'CASE-1018',
    'Requested Date/Time': '2023-06-01T14:25:36Z',
    Type: 'Approval Request',
    'Requested From': 'Management',
    'Assigned To': 'Susan Garcia',
    Status: 'pending',
  },
  {
    'Case ID': 'CASE-1019',
    'Requested Date/Time': '2023-06-02T11:40:21Z',
    Type: 'Audit Support',
    'Requested From': 'Internal Audit',
    'Assigned To': 'Donald Martinez',
    Status: 'completed',
  },
  {
    'Case ID': 'CASE-1020',
    'Requested Date/Time': '2023-06-03T16:50:44Z',
    Type: 'Emergency Access',
    'Requested From': 'Security Operations',
    'Assigned To': 'Margaret Robinson',
    Status: 'escalated',
  },
];
